#!/bin/bash
echo "Configuring GPIO pins"
config-pin -q p8.16
config-pin -l p8.16
config-pin p8.16 gpio_pu
config-pin -q p8.16

echo "Starting build for virtualIndicator.cpp"
g++ virtualIndicator.cpp -lpaho-mqtt3c -o virtualIndicator
echo "Finishing build for virtualIndicator.cpp"
